"""BIOSCAN image-DNA Bridged Clustering experiments."""

from bridged_clustering.bioscan import (
    BIOSCAN_MODEL_NAMES,
    DEVICE,
    BioscanGridSpec,
    BioscanPaths,
    EncoderSuite,
    bkm_regression,
    build_decision_matrix,
    build_parser,
    build_true_decision_vector,
    compute_gene_centroids,
    decisionVector,
    encode_genes,
    encode_genes_for_samples,
    encode_images,
    encode_images_for_samples,
    evaluate_loss,
    get_data_splits,
    knn_regression,
    load_dataset,
    load_encoder_suite,
    load_pretrained_models,
    main,
    perform_clustering,
    perform_inference,
    run_experiment,
    run_reversed_experiment,
    split_family_samples,
)

__all__ = [
    "BIOSCAN_MODEL_NAMES",
    "DEVICE",
    "BioscanGridSpec",
    "BioscanPaths",
    "EncoderSuite",
    "bkm_regression",
    "build_decision_matrix",
    "build_parser",
    "build_true_decision_vector",
    "compute_gene_centroids",
    "decisionVector",
    "encode_genes",
    "encode_genes_for_samples",
    "encode_images",
    "encode_images_for_samples",
    "evaluate_loss",
    "get_data_splits",
    "knn_regression",
    "load_dataset",
    "load_encoder_suite",
    "load_pretrained_models",
    "main",
    "perform_clustering",
    "perform_inference",
    "run_experiment",
    "run_reversed_experiment",
    "split_family_samples",
]


if __name__ == "__main__":
    main()
